// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POKEMONSEMAPI.Repositories;

#nullable disable

namespace PokemonSemAPI.Migrations
{
    [DbContext(typeof(PokeDbContext))]
    [Migration("20250315171016_AddPokemon")]
    partial class AddPokemon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POKEMONSEMAPI.Models.Pokemon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATKBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("DEFBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("HPBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("NationalDexNumber")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SPATKBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("SPDBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("SPDEFBaseStat")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Pokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
