// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POKEMONSEMAPI.Repositories;

#nullable disable

namespace PokemonSemAPI.Migrations
{
    [DbContext(typeof(PokeDbContext))]
    partial class PokeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POKEMONSEMAPI.Models.PokeDexEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("NationalDexNumber")
                        .HasColumnType("int");

                    b.Property<float>("PokeHeightInMeters")
                        .HasColumnType("real");

                    b.Property<float>("PokeWeightInLbs")
                        .HasColumnType("real");

                    b.Property<string>("PokemonDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonID")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PokemonID");

                    b.ToTable("PokeDexEntries");
                });

            modelBuilder.Entity("POKEMONSEMAPI.Models.Pokemon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATKBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("DEFBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("HPBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("NationalDexNumber")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SPATKBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("SPDBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("SPDEFBaseStat")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("POKEMONSEMAPI.Models.PokeDexEntry", b =>
                {
                    b.HasOne("POKEMONSEMAPI.Models.Pokemon", "Pokemon")
                        .WithMany("PokeDexEntries")
                        .HasForeignKey("PokemonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("POKEMONSEMAPI.Models.Pokemon", b =>
                {
                    b.Navigation("PokeDexEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
