// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POKESEMAPIDatabase.Repositories;

#nullable disable

namespace PokemonSemAPI.Migrations
{
    [DbContext(typeof(PokeDbContext))]
    partial class PokeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POKESEMAPIDatabase.Models.PokemonDex", b =>
                {
                    b.Property<int>("NationalDexNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalDexNumber"));

                    b.Property<int>("ATKBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("DEFBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("HPBaseStat")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SPATKBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("SPDBaseStat")
                        .HasColumnType("int");

                    b.Property<int>("SPDEFBaseStat")
                        .HasColumnType("int");

                    b.HasKey("NationalDexNumber");

                    b.ToTable("PokeDexEntries");
                });

            modelBuilder.Entity("POKESEMAPIDatabase.Models.PokemonIndividual", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATKEV")
                        .HasColumnType("int");

                    b.Property<int>("ATKIV")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("BuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DEFEV")
                        .HasColumnType("int");

                    b.Property<int>("DEFIV")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("HPEV")
                        .HasColumnType("int");

                    b.Property<int>("HPIV")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonDexNationalDexNumber")
                        .HasColumnType("int");

                    b.Property<int>("PokemonLevel")
                        .HasColumnType("int");

                    b.Property<int>("SPATKEV")
                        .HasColumnType("int");

                    b.Property<int>("SPATKIV")
                        .HasColumnType("int");

                    b.Property<int>("SPDEFEV")
                        .HasColumnType("int");

                    b.Property<int>("SPDEFIV")
                        .HasColumnType("int");

                    b.Property<int>("SPDEV")
                        .HasColumnType("int");

                    b.Property<int>("SPDIV")
                        .HasColumnType("int");

                    b.Property<int>("SpAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PokemonDexNationalDexNumber");

                    b.ToTable("PokeIndividual");
                });

            modelBuilder.Entity("POKESEMAPIDatabase.Models.PokemonIndividual", b =>
                {
                    b.HasOne("POKESEMAPIDatabase.Models.PokemonDex", "PokemonDex")
                        .WithMany("PokemonInstance")
                        .HasForeignKey("PokemonDexNationalDexNumber");

                    b.Navigation("PokemonDex");
                });

            modelBuilder.Entity("POKESEMAPIDatabase.Models.PokemonDex", b =>
                {
                    b.Navigation("PokemonInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
